name: Update gh-pages
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update gh-pages
        run: |
          git branch -D gh-pages
          git checkout -b gh-pages
          git push -f origin gh-pages
